import ProductImg1 from '../public/products/1.webp';
import ProductImg2 from '../public/products/2.webp';
import ProductImg3 from '../public/products/3.webp';
import ProductImg4 from '../public/products/4.webp';
import ProductImg5 from '../public/products/5.webp';
import ProductImg150 from '../public/products/150.webp';

export const products = [
    {
      id: 1,
      image: ProductImg1,
      title: "Palworld (Global) (PC) - Steam - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "5,797.99",
      discountedPrice: "5,391.14",
      discountPercentage: "7%",
      currency: "DZD"
    },
    {
      id: 2,
      image: ProductImg2,
      title: "EA SPORTS FC 24 (Global) (PC) - EA App - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "7,999.99",
      discountedPrice: "5,999.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 3,
      image: ProductImg3,
      title: "The Last of Us Part II",
      platform: "PS5, PS4",
      region: "Global",
      originalPrice: "6,499.99",
      discountedPrice: "5,199.99",
      discountPercentage: "20%",
      currency: "DZD"
    },
    {
      id: 4,
      image: ProductImg4,
      title: "Red Dead Redemption 2",
      platform: "PC, PS4, Xbox One",
      region: "Global",
      originalPrice: "4,399.99",
      discountedPrice: "3,299.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 5,
      image: ProductImg5,
      title: "Hogwarts Legacy",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "8,499.99",
      discountedPrice: "6,374.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 6,
      image: ProductImg150,
      title: "Cyberpunk 2077",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "5,999.99",
      discountedPrice: "3,599.99",
      discountPercentage: "40%",
      currency: "DZD"
    },
    {
      id: 7,
      image: ProductImg1,
      title: "Palworld (Global) (PC) - Steam - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "5,797.99",
      discountedPrice: "5,391.14",
      discountPercentage: "7%",
      currency: "DZD"
    },
    {
      id: 8,
      image: ProductImg2,
      title: "EA SPORTS FC 24 (Global) (PC) - EA App - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "7,999.99",
      discountedPrice: "5,999.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 9,
      image: ProductImg3,
      title: "The Last of Us Part II",
      platform: "PS5, PS4",
      region: "Global",
      originalPrice: "6,499.99",
      discountedPrice: "5,199.99",
      discountPercentage: "20%",
      currency: "DZD"
    },
    {
      id: 10,
      image: ProductImg4,
      title: "Red Dead Redemption 2",
      platform: "PC, PS4, Xbox One",
      region: "Global",
      originalPrice: "4,399.99",
      discountedPrice: "3,299.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 11,
      image: ProductImg5,
      title: "Hogwarts Legacy",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "8,499.99",
      discountedPrice: "6,374.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 12,
      image: ProductImg150,
      title: "Cyberpunk 2077",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "5,999.99",
      discountedPrice: "3,599.99",
      discountPercentage: "40%",
      currency: "DZD"
    },
    {
      id: 7,
      image: ProductImg1,
      title: "Palworld (Global) (PC) - Steam - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "5,797.99",
      discountedPrice: "5,391.14",
      discountPercentage: "7%",
      currency: "DZD"
    },
    {
      id: 8,
      image: ProductImg2,
      title: "EA SPORTS FC 24 (Global) (PC) - EA App - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "7,999.99",
      discountedPrice: "5,999.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 9,
      image: ProductImg3,
      title: "The Last of Us Part II",
      platform: "PS5, PS4",
      region: "Global",
      originalPrice: "6,499.99",
      discountedPrice: "5,199.99",
      discountPercentage: "20%",
      currency: "DZD"
    },
    {
      id: 10,
      image: ProductImg4,
      title: "Red Dead Redemption 2",
      platform: "PC, PS4, Xbox One",
      region: "Global",
      originalPrice: "4,399.99",
      discountedPrice: "3,299.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 11,
      image: ProductImg5,
      title: "Hogwarts Legacy",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "8,499.99",
      discountedPrice: "6,374.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 12,
      image: ProductImg150,
      title: "Cyberpunk 2077",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "5,999.99",
      discountedPrice: "3,599.99",
      discountPercentage: "40%",
      currency: "DZD"
    },
    {
      id: 7,
      image: ProductImg1,
      title: "Palworld (Global) (PC) - Steam - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "5,797.99",
      discountedPrice: "5,391.14",
      discountPercentage: "7%",
      currency: "DZD"
    },
    {
      id: 8,
      image: ProductImg2,
      title: "EA SPORTS FC 24 (Global) (PC) - EA App - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "7,999.99",
      discountedPrice: "5,999.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 9,
      image: ProductImg3,
      title: "The Last of Us Part II",
      platform: "PS5, PS4",
      region: "Global",
      originalPrice: "6,499.99",
      discountedPrice: "5,199.99",
      discountPercentage: "20%",
      currency: "DZD"
    },
    {
      id: 10,
      image: ProductImg4,
      title: "Red Dead Redemption 2",
      platform: "PC, PS4, Xbox One",
      region: "Global",
      originalPrice: "4,399.99",
      discountedPrice: "3,299.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 11,
      image: ProductImg5,
      title: "Hogwarts Legacy",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "8,499.99",
      discountedPrice: "6,374.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 12,
      image: ProductImg150,
      title: "Cyberpunk 2077",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "5,999.99",
      discountedPrice: "3,599.99",
      discountPercentage: "40%",
      currency: "DZD"
    },
    {
      id: 7,
      image: ProductImg1,
      title: "Palworld (Global) (PC) - Steam - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "5,797.99",
      discountedPrice: "5,391.14",
      discountPercentage: "7%",
      currency: "DZD"
    },
    {
      id: 8,
      image: ProductImg2,
      title: "EA SPORTS FC 24 (Global) (PC) - EA App - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "7,999.99",
      discountedPrice: "5,999.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 9,
      image: ProductImg3,
      title: "The Last of Us Part II",
      platform: "PS5, PS4",
      region: "Global",
      originalPrice: "6,499.99",
      discountedPrice: "5,199.99",
      discountPercentage: "20%",
      currency: "DZD"
    },
    {
      id: 10,
      image: ProductImg4,
      title: "Red Dead Redemption 2",
      platform: "PC, PS4, Xbox One",
      region: "Global",
      originalPrice: "4,399.99",
      discountedPrice: "3,299.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 11,
      image: ProductImg5,
      title: "Hogwarts Legacy",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "8,499.99",
      discountedPrice: "6,374.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 12,
      image: ProductImg150,
      title: "Cyberpunk 2077",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "5,999.99",
      discountedPrice: "3,599.99",
      discountPercentage: "40%",
      currency: "DZD"
    },
    {
      id: 7,
      image: ProductImg1,
      title: "Palworld (Global) (PC) - Steam - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "5,797.99",
      discountedPrice: "5,391.14",
      discountPercentage: "7%",
      currency: "DZD"
    },
    {
      id: 8,
      image: ProductImg2,
      title: "EA SPORTS FC 24 (Global) (PC) - EA App - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "7,999.99",
      discountedPrice: "5,999.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 9,
      image: ProductImg3,
      title: "The Last of Us Part II",
      platform: "PS5, PS4",
      region: "Global",
      originalPrice: "6,499.99",
      discountedPrice: "5,199.99",
      discountPercentage: "20%",
      currency: "DZD"
    },
    {
      id: 10,
      image: ProductImg4,
      title: "Red Dead Redemption 2",
      platform: "PC, PS4, Xbox One",
      region: "Global",
      originalPrice: "4,399.99",
      discountedPrice: "3,299.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 11,
      image: ProductImg5,
      title: "Hogwarts Legacy",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "8,499.99",
      discountedPrice: "6,374.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 12,
      image: ProductImg150,
      title: "Cyberpunk 2077",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "5,999.99",
      discountedPrice: "3,599.99",
      discountPercentage: "40%",
      currency: "DZD"
    },
    {
      id: 7,
      image: ProductImg1,
      title: "Palworld (Global) (PC) - Steam - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "5,797.99",
      discountedPrice: "5,391.14",
      discountPercentage: "7%",
      currency: "DZD"
    },
    {
      id: 8,
      image: ProductImg2,
      title: "EA SPORTS FC 24 (Global) (PC) - EA App - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "7,999.99",
      discountedPrice: "5,999.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 9,
      image: ProductImg3,
      title: "The Last of Us Part II",
      platform: "PS5, PS4",
      region: "Global",
      originalPrice: "6,499.99",
      discountedPrice: "5,199.99",
      discountPercentage: "20%",
      currency: "DZD"
    },
    {
      id: 10,
      image: ProductImg4,
      title: "Red Dead Redemption 2",
      platform: "PC, PS4, Xbox One",
      region: "Global",
      originalPrice: "4,399.99",
      discountedPrice: "3,299.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 11,
      image: ProductImg5,
      title: "Hogwarts Legacy",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "8,499.99",
      discountedPrice: "6,374.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 12,
      image: ProductImg150,
      title: "Cyberpunk 2077",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "5,999.99",
      discountedPrice: "3,599.99",
      discountPercentage: "40%",
      currency: "DZD"
    },
    {
      id: 7,
      image: ProductImg1,
      title: "Palworld (Global) (PC) - Steam - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "5,797.99",
      discountedPrice: "5,391.14",
      discountPercentage: "7%",
      currency: "DZD"
    },
    {
      id: 8,
      image: ProductImg2,
      title: "EA SPORTS FC 24 (Global) (PC) - EA App - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "7,999.99",
      discountedPrice: "5,999.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 9,
      image: ProductImg3,
      title: "The Last of Us Part II",
      platform: "PS5, PS4",
      region: "Global",
      originalPrice: "6,499.99",
      discountedPrice: "5,199.99",
      discountPercentage: "20%",
      currency: "DZD"
    },
    {
      id: 10,
      image: ProductImg4,
      title: "Red Dead Redemption 2",
      platform: "PC, PS4, Xbox One",
      region: "Global",
      originalPrice: "4,399.99",
      discountedPrice: "3,299.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 11,
      image: ProductImg5,
      title: "Hogwarts Legacy",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "8,499.99",
      discountedPrice: "6,374.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 12,
      image: ProductImg150,
      title: "Cyberpunk 2077",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "5,999.99",
      discountedPrice: "3,599.99",
      discountPercentage: "40%",
      currency: "DZD"
    },
    {
      id: 7,
      image: ProductImg1,
      title: "Palworld (Global) (PC) - Steam - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "5,797.99",
      discountedPrice: "5,391.14",
      discountPercentage: "7%",
      currency: "DZD"
    },
    {
      id: 8,
      image: ProductImg2,
      title: "EA SPORTS FC 24 (Global) (PC) - EA App - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "7,999.99",
      discountedPrice: "5,999.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 9,
      image: ProductImg3,
      title: "The Last of Us Part II",
      platform: "PS5, PS4",
      region: "Global",
      originalPrice: "6,499.99",
      discountedPrice: "5,199.99",
      discountPercentage: "20%",
      currency: "DZD"
    },
    {
      id: 10,
      image: ProductImg4,
      title: "Red Dead Redemption 2",
      platform: "PC, PS4, Xbox One",
      region: "Global",
      originalPrice: "4,399.99",
      discountedPrice: "3,299.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 11,
      image: ProductImg5,
      title: "Hogwarts Legacy",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "8,499.99",
      discountedPrice: "6,374.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 12,
      image: ProductImg150,
      title: "Cyberpunk 2077",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "5,999.99",
      discountedPrice: "3,599.99",
      discountPercentage: "40%",
      currency: "DZD"
    },
    {
      id: 7,
      image: ProductImg1,
      title: "Palworld (Global) (PC) - Steam - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "5,797.99",
      discountedPrice: "5,391.14",
      discountPercentage: "7%",
      currency: "DZD"
    },
    {
      id: 8,
      image: ProductImg2,
      title: "EA SPORTS FC 24 (Global) (PC) - EA App - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "7,999.99",
      discountedPrice: "5,999.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 9,
      image: ProductImg3,
      title: "The Last of Us Part II",
      platform: "PS5, PS4",
      region: "Global",
      originalPrice: "6,499.99",
      discountedPrice: "5,199.99",
      discountPercentage: "20%",
      currency: "DZD"
    },
    {
      id: 10,
      image: ProductImg4,
      title: "Red Dead Redemption 2",
      platform: "PC, PS4, Xbox One",
      region: "Global",
      originalPrice: "4,399.99",
      discountedPrice: "3,299.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 11,
      image: ProductImg5,
      title: "Hogwarts Legacy",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "8,499.99",
      discountedPrice: "6,374.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 12,
      image: ProductImg150,
      title: "Cyberpunk 2077",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "5,999.99",
      discountedPrice: "3,599.99",
      discountPercentage: "40%",
      currency: "DZD"
    },
    {
      id: 7,
      image: ProductImg1,
      title: "Palworld (Global) (PC) - Steam - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "5,797.99",
      discountedPrice: "5,391.14",
      discountPercentage: "7%",
      currency: "DZD"
    },
    {
      id: 8,
      image: ProductImg2,
      title: "EA SPORTS FC 24 (Global) (PC) - EA App - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "7,999.99",
      discountedPrice: "5,999.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 9,
      image: ProductImg3,
      title: "The Last of Us Part II",
      platform: "PS5, PS4",
      region: "Global",
      originalPrice: "6,499.99",
      discountedPrice: "5,199.99",
      discountPercentage: "20%",
      currency: "DZD"
    },
    {
      id: 10,
      image: ProductImg4,
      title: "Red Dead Redemption 2",
      platform: "PC, PS4, Xbox One",
      region: "Global",
      originalPrice: "4,399.99",
      discountedPrice: "3,299.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 11,
      image: ProductImg5,
      title: "Hogwarts Legacy",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "8,499.99",
      discountedPrice: "6,374.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 12,
      image: ProductImg150,
      title: "Cyberpunk 2077",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "5,999.99",
      discountedPrice: "3,599.99",
      discountPercentage: "40%",
      currency: "DZD"
    },
    {
      id: 7,
      image: ProductImg1,
      title: "Palworld (Global) (PC) - Steam - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "5,797.99",
      discountedPrice: "5,391.14",
      discountPercentage: "7%",
      currency: "DZD"
    },
    {
      id: 8,
      image: ProductImg2,
      title: "EA SPORTS FC 24 (Global) (PC) - EA App - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "7,999.99",
      discountedPrice: "5,999.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 9,
      image: ProductImg3,
      title: "The Last of Us Part II",
      platform: "PS5, PS4",
      region: "Global",
      originalPrice: "6,499.99",
      discountedPrice: "5,199.99",
      discountPercentage: "20%",
      currency: "DZD"
    },
    {
      id: 10,
      image: ProductImg4,
      title: "Red Dead Redemption 2",
      platform: "PC, PS4, Xbox One",
      region: "Global",
      originalPrice: "4,399.99",
      discountedPrice: "3,299.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 11,
      image: ProductImg5,
      title: "Hogwarts Legacy",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "8,499.99",
      discountedPrice: "6,374.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 12,
      image: ProductImg150,
      title: "Cyberpunk 2077",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "5,999.99",
      discountedPrice: "3,599.99",
      discountPercentage: "40%",
      currency: "DZD"
    },
    {
      id: 7,
      image: ProductImg1,
      title: "Palworld (Global) (PC) - Steam - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "5,797.99",
      discountedPrice: "5,391.14",
      discountPercentage: "7%",
      currency: "DZD"
    },
    {
      id: 8,
      image: ProductImg2,
      title: "EA SPORTS FC 24 (Global) (PC) - EA App - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "7,999.99",
      discountedPrice: "5,999.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 9,
      image: ProductImg3,
      title: "The Last of Us Part II",
      platform: "PS5, PS4",
      region: "Global",
      originalPrice: "6,499.99",
      discountedPrice: "5,199.99",
      discountPercentage: "20%",
      currency: "DZD"
    },
    {
      id: 10,
      image: ProductImg4,
      title: "Red Dead Redemption 2",
      platform: "PC, PS4, Xbox One",
      region: "Global",
      originalPrice: "4,399.99",
      discountedPrice: "3,299.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 11,
      image: ProductImg5,
      title: "Hogwarts Legacy",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "8,499.99",
      discountedPrice: "6,374.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 12,
      image: ProductImg150,
      title: "Cyberpunk 2077",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "5,999.99",
      discountedPrice: "3,599.99",
      discountPercentage: "40%",
      currency: "DZD"
    },
    {
      id: 7,
      image: ProductImg1,
      title: "Palworld (Global) (PC) - Steam - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "5,797.99",
      discountedPrice: "5,391.14",
      discountPercentage: "7%",
      currency: "DZD"
    },
    {
      id: 8,
      image: ProductImg2,
      title: "EA SPORTS FC 24 (Global) (PC) - EA App - Digital Key",
      platform: "PC",
      region: "Global",
      originalPrice: "7,999.99",
      discountedPrice: "5,999.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 9,
      image: ProductImg3,
      title: "The Last of Us Part II",
      platform: "PS5, PS4",
      region: "Global",
      originalPrice: "6,499.99",
      discountedPrice: "5,199.99",
      discountPercentage: "20%",
      currency: "DZD"
    },
    {
      id: 10,
      image: ProductImg4,
      title: "Red Dead Redemption 2",
      platform: "PC, PS4, Xbox One",
      region: "Global",
      originalPrice: "4,399.99",
      discountedPrice: "3,299.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 11,
      image: ProductImg5,
      title: "Hogwarts Legacy",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "8,499.99",
      discountedPrice: "6,374.99",
      discountPercentage: "25%",
      currency: "DZD"
    },
    {
      id: 12,
      image: ProductImg150,
      title: "Cyberpunk 2077",
      platform: "PC, PS5, Xbox Series X/S",
      region: "Global",
      originalPrice: "5,999.99",
      discountedPrice: "3,599.99",
      discountPercentage: "40%",
      currency: "DZD"
    },
  
  ];
  